
var ConfiguratorKernel = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(ConfiguratorKernel) {
  ConfiguratorKernel = ConfiguratorKernel || {};


var k;k||(k=typeof ConfiguratorKernel !== 'undefined' ? ConfiguratorKernel : {});var aa,ba;k.ready=new Promise(function(a,b){aa=a;ba=b});var ca=Object.assign({},k),da="./this.program",ea=(a,b)=>{throw b;},q="";"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src);_scriptDir&&(q=_scriptDir);0!==q.indexOf("blob:")?q=q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):q="";var fa=k.print||console.log.bind(console),r=k.printErr||console.warn.bind(console);Object.assign(k,ca);
ca=null;k.thisProgram&&(da=k.thisProgram);k.quit&&(ea=k.quit);var t=0,ha;k.wasmBinary&&(ha=k.wasmBinary);var noExitRuntime=k.noExitRuntime||!0;"object"!=typeof WebAssembly&&ia("no native wasm support detected");var ja,ka=!1,la="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ma(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&la)return la.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function na(a,b,c,d){if(0<d){d=c+d-1;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var h=a.charCodeAt(++e);f=65536+((f&1023)<<10)|h&1023}if(127>=f){if(c>=d)break;b[c++]=f}else{if(2047>=f){if(c+1>=d)break;b[c++]=192|f>>6}else{if(65535>=f){if(c+2>=d)break;b[c++]=224|f>>12}else{if(c+3>=d)break;b[c++]=240|f>>18;b[c++]=128|f>>12&63}b[c++]=128|f>>6&63}b[c++]=128|f&63}}b[c]=0}}
function oa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var pa="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function qa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&ra[c];)++c;c<<=1;if(32<c-a&&pa)return pa.decode(u.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=y[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}
function sa(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)y[b>>1]=a.charCodeAt(e),b+=2;y[b>>1]=0;return b-d}function ta(a){return 2*a.length}function ua(a,b){for(var c=0,d="";!(c>=b/4);){var e=A[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function va(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var h=a.charCodeAt(++e);f=65536+((f&1023)<<10)|h&1023}A[b>>2]=f;b+=4;if(b+4>c)break}A[b>>2]=0;return b-d}function wa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var xa,B,u,y,ra,A,D,ya,za;
function Aa(){var a=ja.buffer;xa=a;k.HEAP8=B=new Int8Array(a);k.HEAP16=y=new Int16Array(a);k.HEAP32=A=new Int32Array(a);k.HEAPU8=u=new Uint8Array(a);k.HEAPU16=ra=new Uint16Array(a);k.HEAPU32=D=new Uint32Array(a);k.HEAPF32=ya=new Float32Array(a);k.HEAPF64=za=new Float64Array(a)}var Ba,Ca=[],Da=[],Ea=[],Fa=[];function Ga(){var a=k.preRun.shift();Ca.unshift(a)}var E=0,Ha=null,Ia=null;k.preloadedImages={};k.preloadedAudios={};
function ia(a){if(k.onAbort)k.onAbort(a);a="Aborted("+a+")";r(a);ka=!0;a=new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Ja(){return F.startsWith("data:application/octet-stream;base64,")}var F;F="ConfiguratorKernel.wasm";if(!Ja()){var Ka=F;F=k.locateFile?k.locateFile(Ka,q):q+Ka}function La(){var a=F;try{if(a==F&&ha)return new Uint8Array(ha);throw"both async and sync fetching of the wasm failed";}catch(b){ia(b)}}
function Ma(){return ha||"function"!=typeof fetch?Promise.resolve().then(function(){return La()}):fetch(F,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+F+"'";return a.arrayBuffer()}).catch(function(){return La()})}function Na(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(k);else{var c=b.hd;"number"==typeof c?void 0===b.xc?G(c)():G(c)(b.xc):c(void 0===b.xc?null:b.xc)}}}function G(a){return Ba.get(a)}
function H(a){this.Ec=a;this.Rb=a-16;this.vc=function(b){A[this.Rb+4>>2]=b};this.kc=function(){return A[this.Rb+4>>2]};this.bc=function(b){A[this.Rb+8>>2]=b};this.Pc=function(){return A[this.Rb+8>>2]};this.dc=function(){A[this.Rb>>2]=0};this.Cc=function(b){B[this.Rb+12>>0]=b?1:0};this.Oc=function(){return 0!=B[this.Rb+12>>0]};this.rc=function(b){B[this.Rb+13>>0]=b?1:0};this.Gc=function(){return 0!=B[this.Rb+13>>0]};this.ac=function(b,c){this.vc(b);this.bc(c);this.dc();this.Cc(!1);this.rc(!1)};this.wc=
function(){A[this.Rb>>2]+=1};this.Yc=function(){var b=A[this.Rb>>2];A[this.Rb>>2]=b-1;return 1===b}}
function Oa(a){this.yc=function(){J(this.Rb);this.Rb=0};this.bc=function(b){A[this.Rb>>2]=b};this.fc=function(){return A[this.Rb>>2]};this.ac=function(b){A[this.Rb+4>>2]=b};this.dc=function(){return this.Rb+4};this.vc=function(){return A[this.Rb+4>>2]};this.Ic=function(){if(Pa(this.hc().kc()))return A[this.fc()>>2];var b=this.vc();return 0!==b?b:this.fc()};this.hc=function(){return new H(this.fc())};void 0===a?(this.Rb=Qa(8),this.ac(0)):this.Rb=a}var K=[],Ra=0;
function Sa(a){return J((new H(a)).Rb)}function Ta(a){if(a.Yc()&&!a.Gc()){var b=a.Pc();b&&G(b)(a.Ec);Sa(a.Ec)}}var L=0;function Ua(){var a=K.pop();a||ia("no exception to throw");var b=a.hc(),c=a.fc();b.Gc()?a.yc():(K.push(a),b.rc(!0),b.Cc(!1),Ra++);L=c;throw c;}var Va={};function Wa(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Xa(a){return this.fromWireType(D[a>>2])}var Ya={},Za={},$a={};
function ab(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function bb(a,b){a=ab(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function cb(a){var b=Error,c=bb(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var db=void 0;function eb(a){throw new db(a);}
function M(a,b,c){function d(g){g=c(g);g.length!==a.length&&eb("Mismatched type converter count");for(var m=0;m<a.length;++m)N(a[m],g[m])}a.forEach(function(g){$a[g]=b});var e=Array(b.length),f=[],h=0;b.forEach(function(g,m){Za.hasOwnProperty(g)?e[m]=Za[g]:(f.push(g),Ya.hasOwnProperty(g)||(Ya[g]=[]),Ya[g].push(function(){e[m]=Za[g];++h;h===f.length&&d(e)}))});0===f.length&&d(e)}
function fb(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var gb=void 0;function O(a){for(var b="";u[a];)b+=gb[u[a++]];return b}var hb=void 0;function P(a){throw new hb(a);}
function N(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||P('type "'+d+'" must have a positive integer typeid pointer');if(Za.hasOwnProperty(a)){if(c.Tc)return;P("Cannot register type '"+d+"' twice")}Za[a]=b;delete $a[a];Ya.hasOwnProperty(a)&&(b=Ya[a],delete Ya[a],b.forEach(function(e){e()}))}function ib(a){P(a.Qb.Tb.Sb.name+" instance already deleted")}var jb=!1;function kb(){}
function lb(a){--a.count.value;0===a.count.value&&(a.Vb?a.Yb.$b(a.Vb):a.Tb.Sb.$b(a.Rb))}function mb(a,b,c){if(b===c)return a;if(void 0===c.Zb)return null;a=mb(a,b,c.Zb);return null===a?null:c.Kc(a)}var nb={},ob=[];function pb(){for(;ob.length;){var a=ob.pop();a.Qb.ec=!1;a["delete"]()}}var qb=void 0,rb={};function sb(a,b){for(void 0===b&&P("ptr should not be undefined");a.Zb;)b=a.nc(b),a=a.Zb;return rb[b]}
function tb(a,b){b.Tb&&b.Rb||eb("makeClassHandle requires ptr and ptrType");!!b.Yb!==!!b.Vb&&eb("Both smartPtrType and smartPtr must be specified");b.count={value:1};return ub(Object.create(a,{Qb:{value:b}}))}function ub(a){if("undefined"===typeof FinalizationRegistry)return ub=b=>b,a;jb=new FinalizationRegistry(b=>{lb(b.Qb)});ub=b=>{var c=b.Qb;c.Vb&&jb.register(b,{Qb:c},b);return b};kb=b=>{jb.unregister(b)};return ub(a)}function Q(){}
function vb(a,b,c){if(void 0===a[b].Ub){var d=a[b];a[b]=function(){a[b].Ub.hasOwnProperty(arguments.length)||P("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].Ub+")!");return a[b].Ub[arguments.length].apply(this,arguments)};a[b].Ub=[];a[b].Ub[d.oc]=d}}
function wb(a,b,c){k.hasOwnProperty(a)?((void 0===c||void 0!==k[a].Ub&&void 0!==k[a].Ub[c])&&P("Cannot register public name '"+a+"' twice"),vb(k,a,a),k.hasOwnProperty(c)&&P("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),k[a].Ub[c]=b):(k[a]=b,void 0!==c&&(k[a].kd=c))}function xb(a,b,c,d,e,f,h,g){this.name=a;this.constructor=b;this.ic=c;this.$b=d;this.Zb=e;this.Mc=f;this.nc=h;this.Kc=g;this.Wc=[]}
function yb(a,b,c){for(;b!==c;)b.nc||P("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.nc(a),b=b.Zb;return a}function zb(a,b){if(null===b)return this.zc&&P("null is not a valid "+this.name),0;b.Qb||P('Cannot pass "'+Ab(b)+'" as a '+this.name);b.Qb.Rb||P("Cannot pass deleted object as a pointer of type "+this.name);return yb(b.Qb.Rb,b.Qb.Tb.Sb,this.Sb)}
function Bb(a,b){if(null===b){this.zc&&P("null is not a valid "+this.name);if(this.qc){var c=this.Ac();null!==a&&a.push(this.$b,c);return c}return 0}b.Qb||P('Cannot pass "'+Ab(b)+'" as a '+this.name);b.Qb.Rb||P("Cannot pass deleted object as a pointer of type "+this.name);!this.pc&&b.Qb.Tb.pc&&P("Cannot convert argument of type "+(b.Qb.Yb?b.Qb.Yb.name:b.Qb.Tb.name)+" to parameter type "+this.name);c=yb(b.Qb.Rb,b.Qb.Tb.Sb,this.Sb);if(this.qc)switch(void 0===b.Qb.Vb&&P("Passing raw pointer to smart pointer is illegal"),
this.bd){case 0:b.Qb.Yb===this?c=b.Qb.Vb:P("Cannot convert argument of type "+(b.Qb.Yb?b.Qb.Yb.name:b.Qb.Tb.name)+" to parameter type "+this.name);break;case 1:c=b.Qb.Vb;break;case 2:if(b.Qb.Yb===this)c=b.Qb.Vb;else{var d=b.clone();c=this.Xc(c,R(function(){d["delete"]()}));null!==a&&a.push(this.$b,c)}break;default:P("Unsupporting sharing policy")}return c}
function Cb(a,b){if(null===b)return this.zc&&P("null is not a valid "+this.name),0;b.Qb||P('Cannot pass "'+Ab(b)+'" as a '+this.name);b.Qb.Rb||P("Cannot pass deleted object as a pointer of type "+this.name);b.Qb.Tb.pc&&P("Cannot convert argument of type "+b.Qb.Tb.name+" to parameter type "+this.name);return yb(b.Qb.Rb,b.Qb.Tb.Sb,this.Sb)}
function S(a,b,c,d,e,f,h,g,m,n,p){this.name=a;this.Sb=b;this.zc=c;this.pc=d;this.qc=e;this.Vc=f;this.bd=h;this.Hc=g;this.Ac=m;this.Xc=n;this.$b=p;e||void 0!==b.Zb?this.toWireType=Bb:(this.toWireType=d?zb:Cb,this.Xb=null)}function Db(a,b,c){k.hasOwnProperty(a)||eb("Replacing nonexistant public symbol");void 0!==k[a].Ub&&void 0!==c?k[a].Ub[c]=b:(k[a]=b,k[a].oc=c)}
function Eb(a,b){var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=k["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=G(b).apply(null,c);return d}}function U(a,b){a=O(a);var c=a.includes("j")?Eb(a,b):G(b);"function"!=typeof c&&P("unknown function pointer with signature "+a+": "+b);return c}var Fb=void 0;function Gb(a){a=Hb(a);var b=O(a);J(a);return b}
function Ib(a,b){function c(f){e[f]||Za[f]||($a[f]?$a[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Fb(a+": "+d.map(Gb).join([", "]));}function Jb(a,b){for(var c=[],d=0;d<a;d++)c.push(A[(b>>2)+d]);return c}
function Kb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=bb(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Lb(a,b,c,d,e){var f=b.length;2>f&&P("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,g=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].Xb){g=!0;break}var m="void"!==b[0].name,n="",p="";for(c=0;c<f-2;++c)n+=(0!==c?", ":"")+"arg"+c,p+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+ab(a)+"("+n+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(f-2)+" args!');\n}\n";g&&(a+="var destructors = [];\n");var w=g?"destructors":"null";n="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[P,d,e,Wa,b[0],b[1]];h&&(a+="var thisWired = classParam.toWireType("+w+", this);\n");for(c=0;c<f-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+w+", arg"+c+"); // "+b[c+2].name+"\n",n.push("argType"+c),d.push(b[c+2]);h&&(p="thisWired"+(0<p.length?", ":"")+p);a+=(m?"var rv = ":"")+"invoker(fn"+(0<p.length?", ":"")+p+");\n";if(g)a+=
"runDestructors(destructors);\n";else for(c=h?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].Xb&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",n.push(f+"_dtor"),d.push(b[c].Xb));m&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");n.push(a+"}\n");return Kb(n).apply(null,d)}var Mb=[],V=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Nb(a){4<a&&0===--V[a].Bc&&(V[a]=void 0,Mb.push(a))}
function W(a){a||P("Cannot use deleted val. handle = "+a);return V[a].value}function R(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Mb.length?Mb.pop():V.length;V[b]={Bc:1,value:a};return b}}
function Ob(a,b,c){switch(b){case 0:return function(d){return this.fromWireType((c?B:u)[d])};case 1:return function(d){return this.fromWireType((c?y:ra)[d>>1])};case 2:return function(d){return this.fromWireType((c?A:D)[d>>2])};default:throw new TypeError("Unknown integer type: "+a);}}function Pb(a,b){var c=Za[a];void 0===c&&P(b+" has unknown type "+Gb(a));return c}function Ab(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Qb(a,b){switch(b){case 2:return function(c){return this.fromWireType(ya[c>>2])};case 3:return function(c){return this.fromWireType(za[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Rb(a,b,c){switch(b){case 0:return c?function(d){return B[d]}:function(d){return u[d]};case 1:return c?function(d){return y[d>>1]}:function(d){return ra[d>>1]};case 2:return c?function(d){return A[d>>2]}:function(d){return D[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function Sb(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=Pb(A[(b>>2)+d],"parameter "+d);return c}var Vb={};function Wb(a){var b=Vb[a];return void 0===b?O(a):b}var Xb=[];
function Yb(){return"object"==typeof globalThis?globalThis:Function("return this")()}function Zb(a){var b=Xb.length;Xb.push(a);return b}var $b=[],ac={},bc={};
function cc(){if(!dc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in bc)void 0===bc[b]?delete a[b]:a[b]=bc[b];var c=[];for(b in a)c.push(b+"="+a[b]);dc=c}return dc}var dc,ec=[null,[],[]],fc={};function gc(a){return 0===a%4&&(0!==a%100||0===a%400)}function hc(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var ic=[31,29,31,30,31,30,31,31,30,31,30,31],jc=[31,28,31,30,31,30,31,31,30,31,30,31];function kc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(gc(a.getFullYear())?ic:jc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function lc(a,b,c,d){function e(l,v,z){for(l="number"==typeof l?l.toString():l||"";l.length<v;)l=z[0]+l;return l}function f(l,v){return e(l,v,"0")}function h(l,v){function z(I){return 0>I?-1:0<I?1:0}var C;0===(C=z(l.getFullYear()-v.getFullYear()))&&0===(C=z(l.getMonth()-v.getMonth()))&&(C=z(l.getDate()-v.getDate()));return C}function g(l){switch(l.getDay()){case 0:return new Date(l.getFullYear()-1,11,29);case 1:return l;case 2:return new Date(l.getFullYear(),0,3);case 3:return new Date(l.getFullYear(),
0,2);case 4:return new Date(l.getFullYear(),0,1);case 5:return new Date(l.getFullYear()-1,11,31);case 6:return new Date(l.getFullYear()-1,11,30)}}function m(l){l=kc(new Date(l.Wb+1900,0,1),l.uc);var v=new Date(l.getFullYear()+1,0,4),z=g(new Date(l.getFullYear(),0,4));v=g(v);return 0>=h(z,l)?0>=h(v,l)?l.getFullYear()+1:l.getFullYear():l.getFullYear()-1}var n=A[d+40>>2];d={ed:A[d>>2],dd:A[d+4>>2],sc:A[d+8>>2],mc:A[d+12>>2],jc:A[d+16>>2],Wb:A[d+20>>2],tc:A[d+24>>2],uc:A[d+28>>2],ld:A[d+32>>2],cd:A[d+
36>>2],fd:n?n?ma(u,n,void 0):"":""};c=c?ma(u,c,void 0):"";n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in n)c=c.replace(new RegExp(p,"g"),n[p]);var w="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
x="January February March April May June July August September October November December".split(" ");n={"%a":function(l){return w[l.tc].substring(0,3)},"%A":function(l){return w[l.tc]},"%b":function(l){return x[l.jc].substring(0,3)},"%B":function(l){return x[l.jc]},"%C":function(l){return f((l.Wb+1900)/100|0,2)},"%d":function(l){return f(l.mc,2)},"%e":function(l){return e(l.mc,2," ")},"%g":function(l){return m(l).toString().substring(2)},"%G":function(l){return m(l)},"%H":function(l){return f(l.sc,
2)},"%I":function(l){l=l.sc;0==l?l=12:12<l&&(l-=12);return f(l,2)},"%j":function(l){return f(l.mc+hc(gc(l.Wb+1900)?ic:jc,l.jc-1),3)},"%m":function(l){return f(l.jc+1,2)},"%M":function(l){return f(l.dd,2)},"%n":function(){return"\n"},"%p":function(l){return 0<=l.sc&&12>l.sc?"AM":"PM"},"%S":function(l){return f(l.ed,2)},"%t":function(){return"\t"},"%u":function(l){return l.tc||7},"%U":function(l){var v=new Date(l.Wb+1900,0,1),z=0===v.getDay()?v:kc(v,7-v.getDay());l=new Date(l.Wb+1900,l.jc,l.mc);return 0>
h(z,l)?f(Math.ceil((31-z.getDate()+(hc(gc(l.getFullYear())?ic:jc,l.getMonth()-1)-31)+l.getDate())/7),2):0===h(z,v)?"01":"00"},"%V":function(l){var v=new Date(l.Wb+1901,0,4),z=g(new Date(l.Wb+1900,0,4));v=g(v);var C=kc(new Date(l.Wb+1900,0,1),l.uc);return 0>h(C,z)?"53":0>=h(v,C)?"01":f(Math.ceil((z.getFullYear()<l.Wb+1900?l.uc+32-z.getDate():l.uc+1-z.getDate())/7),2)},"%w":function(l){return l.tc},"%W":function(l){var v=new Date(l.Wb,0,1),z=1===v.getDay()?v:kc(v,0===v.getDay()?1:7-v.getDay()+1);l=
new Date(l.Wb+1900,l.jc,l.mc);return 0>h(z,l)?f(Math.ceil((31-z.getDate()+(hc(gc(l.getFullYear())?ic:jc,l.getMonth()-1)-31)+l.getDate())/7),2):0===h(z,v)?"01":"00"},"%y":function(l){return(l.Wb+1900).toString().substring(2)},"%Y":function(l){return l.Wb+1900},"%z":function(l){l=l.cd;var v=0<=l;l=Math.abs(l)/60;return(v?"+":"-")+String("0000"+(l/60*100+l%60)).slice(-4)},"%Z":function(l){return l.fd},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(p in n)c.includes(p)&&(c=c.replace(new RegExp(p,
"g"),n[p](d)));c=c.replace(/\0\0/g,"%");p=mc(c);if(p.length>b)return 0;B.set(p,a);return p.length-1}db=k.InternalError=cb("InternalError");for(var nc=Array(256),oc=0;256>oc;++oc)nc[oc]=String.fromCharCode(oc);gb=nc;hb=k.BindingError=cb("BindingError");Q.prototype.isAliasOf=function(a){if(!(this instanceof Q&&a instanceof Q))return!1;var b=this.Qb.Tb.Sb,c=this.Qb.Rb,d=a.Qb.Tb.Sb;for(a=a.Qb.Rb;b.Zb;)c=b.nc(c),b=b.Zb;for(;d.Zb;)a=d.nc(a),d=d.Zb;return b===d&&c===a};
Q.prototype.clone=function(){this.Qb.Rb||ib(this);if(this.Qb.lc)return this.Qb.count.value+=1,this;var a=ub,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.Qb;a=a(c.call(b,d,{Qb:{value:{count:e.count,ec:e.ec,lc:e.lc,Rb:e.Rb,Tb:e.Tb,Vb:e.Vb,Yb:e.Yb}}}));a.Qb.count.value+=1;a.Qb.ec=!1;return a};Q.prototype["delete"]=function(){this.Qb.Rb||ib(this);this.Qb.ec&&!this.Qb.lc&&P("Object already scheduled for deletion");kb(this);lb(this.Qb);this.Qb.lc||(this.Qb.Vb=void 0,this.Qb.Rb=void 0)};
Q.prototype.isDeleted=function(){return!this.Qb.Rb};Q.prototype.deleteLater=function(){this.Qb.Rb||ib(this);this.Qb.ec&&!this.Qb.lc&&P("Object already scheduled for deletion");ob.push(this);1===ob.length&&qb&&qb(pb);this.Qb.ec=!0;return this};k.getInheritedInstanceCount=function(){return Object.keys(rb).length};k.getLiveInheritedInstances=function(){var a=[],b;for(b in rb)rb.hasOwnProperty(b)&&a.push(rb[b]);return a};k.flushPendingDeletes=pb;k.setDelayFunction=function(a){qb=a;ob.length&&qb&&qb(pb)};
S.prototype.Nc=function(a){this.Hc&&(a=this.Hc(a));return a};S.prototype.Dc=function(a){this.$b&&this.$b(a)};S.prototype.argPackAdvance=8;S.prototype.readValueFromPointer=Xa;S.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
S.prototype.fromWireType=function(a){function b(){return this.qc?tb(this.Sb.ic,{Tb:this.Vc,Rb:c,Yb:this,Vb:a}):tb(this.Sb.ic,{Tb:this,Rb:a})}var c=this.Nc(a);if(!c)return this.Dc(a),null;var d=sb(this.Sb,c);if(void 0!==d){if(0===d.Qb.count.value)return d.Qb.Rb=c,d.Qb.Vb=a,d.clone();d=d.clone();this.Dc(a);return d}d=this.Sb.Mc(c);d=nb[d];if(!d)return b.call(this);d=this.pc?d.Jc:d.pointerType;var e=mb(c,this.Sb,d.Sb);return null===e?b.call(this):this.qc?tb(d.Sb.ic,{Tb:d,Rb:e,Yb:this,Vb:a}):tb(d.Sb.ic,
{Tb:d,Rb:e})};Fb=k.UnboundTypeError=cb("UnboundTypeError");k.count_emval_handles=function(){for(var a=0,b=5;b<V.length;++b)void 0!==V[b]&&++a;return a};k.get_first_emval=function(){for(var a=5;a<V.length;++a)if(void 0!==V[a])return V[a];return null};function mc(a){var b=Array(oa(a)+1);na(a,b,0,b.length);return b}
var Cd={n:function(a){return Qa(a+16)+16},p:function(a){a=new Oa(a);var b=a.hc();b.Oc()||(b.Cc(!0),Ra--);b.rc(!1);K.push(a);b.wc();return a.Ic()},Ka:function(a){r("Unexpected exception thrown, this is not properly supported - aborting");ka=!0;throw a;},Qa:function(){if(!K.length)return 0;var a=K[K.length-1];a.hc().wc();return a.fc()},xa:function(a){a&&Ta(new H(a))},u:function(){X(0);var a=K.pop();Ta(a.hc());a.yc();L=0},b:function(){var a=L;if(!a)return t=0;var b=(new H(a)).kc(),c=new Oa;c.bc(a);c.ac(a);
if(!b)return t=0,c.Rb|0;a=Array.prototype.slice.call(arguments);for(var d=0;d<a.length;d++){var e=a[d];if(0===e||e===b)break;if(pc(e,b,c.dc()))return t=e,c.Rb|0}t=b;return c.Rb|0},i:function(){var a=L;if(!a)return t=0;var b=(new H(a)).kc(),c=new Oa;c.bc(a);c.ac(a);if(!b)return t=0,c.Rb|0;a=Array.prototype.slice.call(arguments);for(var d=0;d<a.length;d++){var e=a[d];if(0===e||e===b)break;if(pc(e,b,c.dc()))return t=e,c.Rb|0}t=b;return c.Rb|0},G:function(){var a=L;if(!a)return t=0;var b=(new H(a)).kc(),
c=new Oa;c.bc(a);c.ac(a);if(!b)return t=0,c.Rb|0;a=Array.prototype.slice.call(arguments);for(var d=0;d<a.length;d++){var e=a[d];if(0===e||e===b)break;if(pc(e,b,c.dc()))return t=e,c.Rb|0}t=b;return c.Rb|0},da:function(){var a=L;if(!a)return t=0;var b=(new H(a)).kc(),c=new Oa;c.bc(a);c.ac(a);if(!b)return t=0,c.Rb|0;a=Array.prototype.slice.call(arguments);for(var d=0;d<a.length;d++){var e=a[d];if(0===e||e===b)break;if(pc(e,b,c.dc()))return t=e,c.Rb|0}t=b;return c.Rb|0},o:Sa,wa:function(a){a&&(new H(a)).wc()},
va:Ua,Pa:function(a){if(a){var b=new Oa;b.bc(a);a=b.hc();K.push(b);a.rc(!0);Ua()}},A:function(a,b,c){(new H(a)).ac(b,c);L=a;Ra++;throw a;},Ra:function(){return Ra},e:function(a){a=new Oa(a);var b=a.fc();L||(L=b);a.yc();throw b;},_a:function(a){var b=Va[a];delete Va[a];var c=b.Ac,d=b.$b,e=b.Fc,f=e.map(function(h){return h.Sc}).concat(e.map(function(h){return h.$c}));M([a],f,function(h){var g={};e.forEach(function(m,n){var p=h[n],w=m.Qc,x=m.Rc,l=h[n+e.length],v=m.Zc,z=m.ad;g[m.Lc]={read:function(C){return p.fromWireType(w(x,
C))},write:function(C,I){var T=[];v(z,C,l.toWireType(T,I));Wa(T)}}});return[{name:b.name,fromWireType:function(m){var n={},p;for(p in g)n[p]=g[p].read(m);d(m);return n},toWireType:function(m,n){for(var p in g)if(!(p in n))throw new TypeError('Missing field:  "'+p+'"');var w=c();for(p in g)g[p].write(w,n[p]);null!==m&&m.push(d,w);return w},argPackAdvance:8,readValueFromPointer:Xa,Xb:d}]})},ib:function(){},Va:function(a,b,c,d,e){var f=fb(c);b=O(b);N(a,{name:b,fromWireType:function(h){return!!h},toWireType:function(h,
g){return g?d:e},argPackAdvance:8,readValueFromPointer:function(h){if(1===c)var g=B;else if(2===c)g=y;else if(4===c)g=A;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(g[h>>f])},Xb:null})},z:function(a,b,c,d,e,f,h,g,m,n,p,w,x){p=O(p);f=U(e,f);g&&(g=U(h,g));n&&(n=U(m,n));x=U(w,x);var l=ab(p);wb(l,function(){Ib("Cannot construct "+p+" due to unbound types",[d])});M([a,b,c],d?[d]:[],function(v){v=v[0];if(d){var z=v.Sb;var C=z.ic}else C=Q.prototype;v=bb(l,function(){if(Object.getPrototypeOf(this)!==
I)throw new hb("Use 'new' to construct "+p);if(void 0===T.cc)throw new hb(p+" has no accessible constructor");var Tb=T.cc[arguments.length];if(void 0===Tb)throw new hb("Tried to invoke ctor of "+p+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(T.cc).toString()+") parameters instead!");return Tb.apply(this,arguments)});var I=Object.create(C,{constructor:{value:v}});v.prototype=I;var T=new xb(p,v,I,x,z,f,g,n);z=new S(p,T,!0,!1,!1);C=new S(p+"*",T,!1,!1,!1);var Ub=
new S(p+" const*",T,!1,!0,!1);nb[a]={pointerType:C,Jc:Ub};Db(l,v);return[z,C,Ub]})},y:function(a,b,c,d,e,f){0<b||ia(void 0);var h=Jb(b,c);e=U(d,e);M([],[a],function(g){g=g[0];var m="constructor "+g.name;void 0===g.Sb.cc&&(g.Sb.cc=[]);if(void 0!==g.Sb.cc[b-1])throw new hb("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+g.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");g.Sb.cc[b-1]=()=>{Ib("Cannot construct "+
g.name+" due to unbound types",h)};M([],h,function(n){n.splice(1,0,null);g.Sb.cc[b-1]=Lb(m,n,null,e,f);return[]});return[]})},m:function(a,b,c,d,e,f,h,g){var m=Jb(c,d);b=O(b);f=U(e,f);M([],[a],function(n){function p(){Ib("Cannot call "+w+" due to unbound types",m)}n=n[0];var w=n.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);g&&n.Sb.Wc.push(b);var x=n.Sb.ic,l=x[b];void 0===l||void 0===l.Ub&&l.className!==n.name&&l.oc===c-2?(p.oc=c-2,p.className=n.name,x[b]=p):(vb(x,b,w),x[b].Ub[c-2]=p);
M([],m,function(v){v=Lb(w,v,n,f,h);void 0===x[b].Ub?(v.oc=c-2,x[b]=v):x[b].Ub[c-2]=v;return[]});return[]})},Ua:function(a,b){b=O(b);N(a,{name:b,fromWireType:function(c){var d=W(c);Nb(c);return d},toWireType:function(c,d){return R(d)},argPackAdvance:8,readValueFromPointer:Xa,Xb:null})},Z:function(a,b,c,d){function e(){}c=fb(c);b=O(b);e.values={};N(a,{name:b,constructor:e,fromWireType:function(f){return this.constructor.values[f]},toWireType:function(f,h){return h.value},argPackAdvance:8,readValueFromPointer:Ob(b,
c,d),Xb:null});wb(b,e)},Y:function(a,b,c){var d=Pb(a,"enum");b=O(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:bb(d.name+"_"+b,function(){})}});a.values[c]=d;a[b]=d},ya:function(a,b,c){c=fb(c);b=O(b);N(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){return e},argPackAdvance:8,readValueFromPointer:Qb(b,c),Xb:null})},aa:function(a,b,c,d,e,f){var h=Jb(b,c);a=O(a);e=U(d,e);wb(a,function(){Ib("Cannot call "+a+" due to unbound types",
h)},b-1);M([],h,function(g){Db(a,Lb(a,[g[0],null].concat(g.slice(1)),null,e,f),b-1);return[]})},O:function(a,b,c,d,e){b=O(b);-1===e&&(e=4294967295);e=fb(c);var f=g=>g;if(0===d){var h=32-8*c;f=g=>g<<h>>>h}c=b.includes("unsigned")?function(g,m){return m>>>0}:function(g,m){return m};N(a,{name:b,fromWireType:f,toWireType:c,argPackAdvance:8,readValueFromPointer:Rb(b,e,0!==d),Xb:null})},I:function(a,b,c){function d(f){f>>=2;var h=D;return new e(xa,h[f+1],h[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,
Int32Array,Uint32Array,Float32Array,Float64Array][b];c=O(c);N(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Tc:!0})},Aa:function(a,b,c,d,e,f,h,g,m,n,p,w){c=O(c);f=U(e,f);g=U(h,g);n=U(m,n);w=U(p,w);M([a],[b],function(x){x=x[0];return[new S(c,x.Sb,!1,!1,!0,x,d,f,g,n,w)]})},za:function(a,b){b=O(b);var c="std::string"===b;N(a,{name:b,fromWireType:function(d){var e=D[d>>2];if(c)for(var f=d+4,h=0;h<=e;++h){var g=d+4+h;if(h==e||0==u[g]){f=f?ma(u,f,g-f):"";if(void 0===m)var m=f;else m+=
String.fromCharCode(0),m+=f;f=g+1}}else{m=Array(e);for(h=0;h<e;++h)m[h]=String.fromCharCode(u[d+4+h]);m=m.join("")}J(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||P("Cannot pass non-string to std::string");var h=(c&&f?()=>oa(e):()=>e.length)(),g=Qa(4+h+1);D[g>>2]=h;if(c&&f)na(e,u,g+4,h+1);else if(f)for(f=0;f<h;++f){var m=e.charCodeAt(f);255<m&&(J(g),
P("String has UTF-16 code units that do not fit in 8 bits"));u[g+4+f]=m}else for(f=0;f<h;++f)u[g+4+f]=e[f];null!==d&&d.push(J,g);return g},argPackAdvance:8,readValueFromPointer:Xa,Xb:function(d){J(d)}})},la:function(a,b,c){c=O(c);if(2===b){var d=qa;var e=sa;var f=ta;var h=()=>ra;var g=1}else 4===b&&(d=ua,e=va,f=wa,h=()=>D,g=2);N(a,{name:c,fromWireType:function(m){for(var n=D[m>>2],p=h(),w,x=m+4,l=0;l<=n;++l){var v=m+4+l*b;if(l==n||0==p[v>>g])x=d(x,v-x),void 0===w?w=x:(w+=String.fromCharCode(0),w+=
x),x=v+b}J(m);return w},toWireType:function(m,n){"string"!=typeof n&&P("Cannot pass non-string to C++ string type "+c);var p=f(n),w=Qa(4+p+b);D[w>>2]=p>>g;e(n,w+4,p+b);null!==m&&m.push(J,w);return w},argPackAdvance:8,readValueFromPointer:Xa,Xb:function(m){J(m)}})},D:function(a,b,c,d,e,f){Va[a]={name:O(b),Ac:U(c,d),$b:U(e,f),Fc:[]}},s:function(a,b,c,d,e,f,h,g,m,n){Va[a].Fc.push({Lc:O(b),Sc:c,Qc:U(d,e),Rc:f,$c:h,Zc:U(g,m),ad:n})},Wa:function(a,b){b=O(b);N(a,{Uc:!0,name:b,argPackAdvance:0,fromWireType:function(){},
toWireType:function(){}})},ma:function(a,b,c){a=W(a);b=Pb(b,"emval::as");var d=[],e=R(d);A[c>>2]=e;return b.toWireType(d,a)},Za:function(a,b,c,d){a=W(a);c=Sb(b,c);for(var e=Array(b),f=0;f<b;++f){var h=c[f];e[f]=h.readValueFromPointer(d);d+=h.argPackAdvance}a=a.apply(void 0,e);return R(a)},S:function(a,b,c,d,e){a=Xb[a];b=W(b);c=Wb(c);var f=[];A[d>>2]=R(f);return a(b,c,f,e)},F:function(a,b,c,d){a=Xb[a];b=W(b);c=Wb(c);a(b,c,null,d)},fa:Nb,Xa:function(a){if(0===a)return R(Yb());a=Wb(a);return R(Yb()[a])},
x:function(a,b){var c=Sb(a,b),d=c[0];b=d.name+"_$"+c.slice(1).map(function(p){return p.name}).join("_")+"$";var e=$b[b];if(void 0!==e)return e;e=["retType"];for(var f=[d],h="",g=0;g<a-1;++g)h+=(0!==g?", ":"")+"arg"+g,e.push("argType"+g),f.push(c[1+g]);var m="return function "+ab("methodCaller_"+b)+"(handle, name, destructors, args) {\n",n=0;for(g=0;g<a-1;++g)m+="    var arg"+g+" = argType"+g+".readValueFromPointer(args"+(n?"+"+n:"")+");\n",n+=c[g+1].argPackAdvance;m+="    var rv = handle[name]("+
h+");\n";for(g=0;g<a-1;++g)c[g+1].deleteObject&&(m+="    argType"+g+".deleteObject(arg"+g+");\n");d.Uc||(m+="    return retType.toWireType(destructors, rv);\n");e.push(m+"};\n");a=Kb(e).apply(null,f);e=Zb(a);return $b[b]=e},ab:function(a){a=Wb(a);return R(k[a])},tb:function(a,b){a=W(a);b=W(b);return R(a[b])},ga:function(a){4<a&&(V[a].Bc+=1)},$a:function(a,b,c,d){a=W(a);var e=ac[b];if(!e){e="";for(var f=0;f<b;++f)e+=(0!==f?", ":"")+"arg"+f;var h="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";
for(f=0;f<b;++f)h+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+f+'], "parameter '+f+'");\nvar arg'+f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType","Module","valueToHandle",h+("var obj = new constructor("+e+");\nreturn valueToHandle(obj);\n}\n")))(Pb,k,R);ac[b]=e}return e(a,c,d)},Ya:function(){return R([])},mb:function(a){return R(Wb(a))},cb:function(a){var b=W(a);Wa(b);Nb(a)},bb:function(a,
b){a=W(a);b=W(b);return a===b},E:function(a,b){a=Pb(a,"_emval_take_value");a=a.readValueFromPointer(b);return R(a)},ja:function(){ia("")},ka:function(a){var b=u.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);e=e.min.call(e,2147483648,d+(65536-d%65536)%65536);a:{try{ja.grow(e-xa.byteLength+65535>>>16);Aa();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},Sa:function(a,b){var c=0;cc().forEach(function(d,e){var f=
b+c;e=A[a+4*e>>2]=f;for(f=0;f<d.length;++f)B[e++>>0]=d.charCodeAt(f);B[e>>0]=0;c+=d.length+1});return 0},Ta:function(a,b){var c=cc();A[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});A[b>>2]=d;return 0},Ma:function(){return 0},Oa:function(a,b,c,d){a=fc.jd(a);b=fc.gd(a,b,c);A[d>>2]=b;return 0},hb:function(){},Na:function(a,b,c,d){for(var e=0,f=0;f<c;f++){var h=A[b>>2],g=A[b+4>>2];b+=8;for(var m=0;m<g;m++){var n=u[h+m],p=ec[a];0===n||10===n?((1===a?fa:r)(ma(p,0)),p.length=0):p.push(n)}e+=
g}A[d>>2]=e;return 0},a:function(){return t},Ja:qc,qa:rc,Da:sc,H:tc,nb:uc,J:vc,pb:wc,V:xc,X:yc,R:zc,W:Ac,Ia:Bc,g:Cc,ia:Dc,ua:Ec,c:Fc,ob:Gc,h:Hc,Ga:Ic,sa:Jc,q:Kc,Ca:Lc,w:Mc,C:Nc,L:Oc,K:Pc,_:Qc,ca:Rc,db:Sc,gb:Tc,k:Uc,l:Vc,oa:Wc,ta:Xc,Fa:Yc,ha:Zc,rb:$c,qb:ad,pa:bd,d:cd,ra:dd,Q:ed,P:fd,Ea:gd,kb:hd,Ha:jd,f:kd,N:ld,sb:md,j:nd,ea:od,lb:pd,na:qd,t:rd,v:sd,B:td,M:ud,U:vd,T:wd,$:xd,jb:yd,ba:zd,eb:Ad,fb:Bd,r:function(a){return a},Ba:function(a){t=a},La:function(a,b,c,d){return lc(a,b,c,d)}};
(function(){function a(e){k.asm=e.exports;ja=k.asm.ub;Aa();Ba=k.asm.Bb;Da.unshift(k.asm.vb);E--;k.monitorRunDependencies&&k.monitorRunDependencies(E);0==E&&(null!==Ha&&(clearInterval(Ha),Ha=null),Ia&&(e=Ia,Ia=null,e()))}function b(e){a(e.instance)}function c(e){return Ma().then(function(f){return WebAssembly.instantiate(f,d)}).then(function(f){return f}).then(e,function(f){r("failed to asynchronously prepare wasm: "+f);ia(f)})}var d={a:Cd};E++;k.monitorRunDependencies&&k.monitorRunDependencies(E);
if(k.instantiateWasm)try{return k.instantiateWasm(d,a)}catch(e){return r("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return ha||"function"!=typeof WebAssembly.instantiateStreaming||Ja()||"function"!=typeof fetch?c(b):fetch(F,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){r("wasm streaming compile failed: "+f);r("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();
k.___wasm_call_ctors=function(){return(k.___wasm_call_ctors=k.asm.vb).apply(null,arguments)};var J=k._free=function(){return(J=k._free=k.asm.wb).apply(null,arguments)},Qa=k._malloc=function(){return(Qa=k._malloc=k.asm.xb).apply(null,arguments)};k._main=function(){return(k._main=k.asm.yb).apply(null,arguments)};var Hb=k.___getTypeName=function(){return(Hb=k.___getTypeName=k.asm.zb).apply(null,arguments)};
k.___embind_register_native_and_builtin_types=function(){return(k.___embind_register_native_and_builtin_types=k.asm.Ab).apply(null,arguments)};
var X=k._setThrew=function(){return(X=k._setThrew=k.asm.Cb).apply(null,arguments)},Y=k.stackSave=function(){return(Y=k.stackSave=k.asm.Db).apply(null,arguments)},Z=k.stackRestore=function(){return(Z=k.stackRestore=k.asm.Eb).apply(null,arguments)},pc=k.___cxa_can_catch=function(){return(pc=k.___cxa_can_catch=k.asm.Fb).apply(null,arguments)},Pa=k.___cxa_is_pointer_type=function(){return(Pa=k.___cxa_is_pointer_type=k.asm.Gb).apply(null,arguments)},Dd=k.dynCall_viiiji=function(){return(Dd=k.dynCall_viiiji=
k.asm.Hb).apply(null,arguments)},Ed=k.dynCall_jii=function(){return(Ed=k.dynCall_jii=k.asm.Ib).apply(null,arguments)},Fd=k.dynCall_iij=function(){return(Fd=k.dynCall_iij=k.asm.Jb).apply(null,arguments)},Gd=k.dynCall_vij=function(){return(Gd=k.dynCall_vij=k.asm.Kb).apply(null,arguments)};k.dynCall_viijii=function(){return(k.dynCall_viijii=k.asm.Lb).apply(null,arguments)};k.dynCall_jiji=function(){return(k.dynCall_jiji=k.asm.Mb).apply(null,arguments)};
k.dynCall_iiiiij=function(){return(k.dynCall_iiiiij=k.asm.Nb).apply(null,arguments)};k.dynCall_iiiiijj=function(){return(k.dynCall_iiiiijj=k.asm.Ob).apply(null,arguments)};k.dynCall_iiiiiijj=function(){return(k.dynCall_iiiiiijj=k.asm.Pb).apply(null,arguments)};function Fc(a,b,c){var d=Y();try{return G(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;X(1,0)}}function kd(a,b,c,d){var e=Y();try{G(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;X(1,0)}}
function nd(a,b,c,d,e){var f=Y();try{G(a)(b,c,d,e)}catch(h){Z(f);if(h!==h+0)throw h;X(1,0)}}function Hc(a,b,c,d){var e=Y();try{return G(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;X(1,0)}}function cd(a,b,c){var d=Y();try{G(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;X(1,0)}}function Vc(a,b){var c=Y();try{G(a)(b)}catch(d){Z(c);if(d!==d+0)throw d;X(1,0)}}function Dc(a,b,c){var d=Y();try{return G(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;X(1,0)}}
function Cc(a,b){var c=Y();try{return G(a)(b)}catch(d){Z(c);if(d!==d+0)throw d;X(1,0)}}function Nc(a,b,c,d,e,f,h){var g=Y();try{return G(a)(b,c,d,e,f,h)}catch(m){Z(g);if(m!==m+0)throw m;X(1,0)}}function Uc(a){var b=Y();try{G(a)()}catch(c){Z(b);if(c!==c+0)throw c;X(1,0)}}function Ec(a,b,c){var d=Y();try{return G(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;X(1,0)}}function zc(a){var b=Y();try{return G(a)()}catch(c){Z(b);if(c!==c+0)throw c;X(1,0)}}
function td(a,b,c,d,e,f,h,g){var m=Y();try{G(a)(b,c,d,e,f,h,g)}catch(n){Z(m);if(n!==n+0)throw n;X(1,0)}}function rd(a,b,c,d,e,f){var h=Y();try{G(a)(b,c,d,e,f)}catch(g){Z(h);if(g!==g+0)throw g;X(1,0)}}function sd(a,b,c,d,e,f,h){var g=Y();try{G(a)(b,c,d,e,f,h)}catch(m){Z(g);if(m!==m+0)throw m;X(1,0)}}function Zc(a,b,c,d,e,f,h,g,m,n,p){var w=Y();try{G(a)(b,c,d,e,f,h,g,m,n,p)}catch(x){Z(w);if(x!==x+0)throw x;X(1,0)}}
function Kc(a,b,c,d,e){var f=Y();try{return G(a)(b,c,d,e)}catch(h){Z(f);if(h!==h+0)throw h;X(1,0)}}function Pc(a,b,c,d,e,f,h,g,m){var n=Y();try{return G(a)(b,c,d,e,f,h,g,m)}catch(p){Z(n);if(p!==p+0)throw p;X(1,0)}}function Mc(a,b,c,d,e,f){var h=Y();try{return G(a)(b,c,d,e,f)}catch(g){Z(h);if(g!==g+0)throw g;X(1,0)}}function ed(a,b,c,d,e){var f=Y();try{G(a)(b,c,d,e)}catch(h){Z(f);if(h!==h+0)throw h;X(1,0)}}
function fd(a,b,c,d,e,f){var h=Y();try{G(a)(b,c,d,e,f)}catch(g){Z(h);if(g!==g+0)throw g;X(1,0)}}function qc(a,b){var c=Y();try{return G(a)(b)}catch(d){Z(c);if(d!==d+0)throw d;X(1,0)}}function vc(a,b,c){var d=Y();try{return G(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;X(1,0)}}function tc(a,b){var c=Y();try{return G(a)(b)}catch(d){Z(c);if(d!==d+0)throw d;X(1,0)}}function Xc(a,b,c,d){var e=Y();try{G(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;X(1,0)}}
function xc(a,b,c,d,e){var f=Y();try{return G(a)(b,c,d,e)}catch(h){Z(f);if(h!==h+0)throw h;X(1,0)}}function Jc(a,b,c,d,e,f,h,g){var m=Y();try{return G(a)(b,c,d,e,f,h,g)}catch(n){Z(m);if(n!==n+0)throw n;X(1,0)}}function ld(a,b,c,d,e,f,h){var g=Y();try{G(a)(b,c,d,e,f,h)}catch(m){Z(g);if(m!==m+0)throw m;X(1,0)}}function Bc(a,b,c,d){var e=Y();try{return G(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;X(1,0)}}
function ud(a,b,c,d,e,f,h,g,m){var n=Y();try{G(a)(b,c,d,e,f,h,g,m)}catch(p){Z(n);if(p!==p+0)throw p;X(1,0)}}function jd(a,b,c,d,e,f,h){var g=Y();try{G(a)(b,c,d,e,f,h)}catch(m){Z(g);if(m!==m+0)throw m;X(1,0)}}function dd(a,b,c,d){var e=Y();try{G(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;X(1,0)}}function od(a,b,c,d,e,f){var h=Y();try{G(a)(b,c,d,e,f)}catch(g){Z(h);if(g!==g+0)throw g;X(1,0)}}function rc(a,b,c){var d=Y();try{return G(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;X(1,0)}}
function Ic(a,b,c,d,e,f,h,g,m,n,p,w,x,l){var v=Y();try{return G(a)(b,c,d,e,f,h,g,m,n,p,w,x,l)}catch(z){Z(v);if(z!==z+0)throw z;X(1,0)}}function Oc(a,b,c,d,e,f,h,g){var m=Y();try{return G(a)(b,c,d,e,f,h,g)}catch(n){Z(m);if(n!==n+0)throw n;X(1,0)}}function bd(a,b,c,d,e,f,h){var g=Y();try{G(a)(b,c,d,e,f,h)}catch(m){Z(g);if(m!==m+0)throw m;X(1,0)}}function xd(a,b,c,d,e,f,h,g,m,n,p,w){var x=Y();try{G(a)(b,c,d,e,f,h,g,m,n,p,w)}catch(l){Z(x);if(l!==l+0)throw l;X(1,0)}}
function Wc(a,b,c){var d=Y();try{G(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;X(1,0)}}function Yc(a,b,c){var d=Y();try{G(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;X(1,0)}}function yc(a,b,c,d){var e=Y();try{return G(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;X(1,0)}}function qd(a,b,c,d,e,f,h){var g=Y();try{G(a)(b,c,d,e,f,h)}catch(m){Z(g);if(m!==m+0)throw m;X(1,0)}}function md(a,b,c,d,e,f){var h=Y();try{G(a)(b,c,d,e,f)}catch(g){Z(h);if(g!==g+0)throw g;X(1,0)}}
function $c(a,b,c,d){var e=Y();try{G(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;X(1,0)}}function ad(a,b,c,d,e,f,h,g){var m=Y();try{G(a)(b,c,d,e,f,h,g)}catch(n){Z(m);if(n!==n+0)throw n;X(1,0)}}function wc(a,b,c,d,e){var f=Y();try{return G(a)(b,c,d,e)}catch(h){Z(f);if(h!==h+0)throw h;X(1,0)}}function Gc(a,b,c,d,e){var f=Y();try{return G(a)(b,c,d,e)}catch(h){Z(f);if(h!==h+0)throw h;X(1,0)}}function Ac(a,b){var c=Y();try{return G(a)(b)}catch(d){Z(c);if(d!==d+0)throw d;X(1,0)}}
function uc(a,b,c){var d=Y();try{return G(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;X(1,0)}}function pd(a,b,c,d,e,f,h,g){var m=Y();try{G(a)(b,c,d,e,f,h,g)}catch(n){Z(m);if(n!==n+0)throw n;X(1,0)}}function gd(a,b,c,d){var e=Y();try{G(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;X(1,0)}}function hd(a,b,c,d,e){var f=Y();try{G(a)(b,c,d,e)}catch(h){Z(f);if(h!==h+0)throw h;X(1,0)}}function vd(a,b,c,d,e,f,h,g,m,n){var p=Y();try{G(a)(b,c,d,e,f,h,g,m,n)}catch(w){Z(p);if(w!==w+0)throw w;X(1,0)}}
function sc(a,b,c,d){var e=Y();try{return G(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;X(1,0)}}function yd(a,b,c,d,e,f,h,g,m,n,p,w,x){var l=Y();try{G(a)(b,c,d,e,f,h,g,m,n,p,w,x)}catch(v){Z(l);if(v!==v+0)throw v;X(1,0)}}function wd(a,b,c,d,e,f,h,g,m,n,p){var w=Y();try{G(a)(b,c,d,e,f,h,g,m,n,p)}catch(x){Z(w);if(x!==x+0)throw x;X(1,0)}}function Qc(a,b,c,d,e,f,h,g,m,n){var p=Y();try{return G(a)(b,c,d,e,f,h,g,m,n)}catch(w){Z(p);if(w!==w+0)throw w;X(1,0)}}
function Lc(a,b,c,d,e,f){var h=Y();try{return G(a)(b,c,d,e,f)}catch(g){Z(h);if(g!==g+0)throw g;X(1,0)}}function Rc(a,b,c,d,e,f,h,g,m,n,p,w){var x=Y();try{return G(a)(b,c,d,e,f,h,g,m,n,p,w)}catch(l){Z(x);if(l!==l+0)throw l;X(1,0)}}function zd(a,b,c,d,e,f,h,g,m,n,p,w,x,l,v,z){var C=Y();try{G(a)(b,c,d,e,f,h,g,m,n,p,w,x,l,v,z)}catch(I){Z(C);if(I!==I+0)throw I;X(1,0)}}function Tc(a,b,c){var d=Y();try{return Ed(a,b,c)}catch(e){Z(d);if(e!==e+0)throw e;X(1,0)}}
function Bd(a,b,c,d){var e=Y();try{Gd(a,b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;X(1,0)}}function Ad(a,b,c,d,e,f,h){var g=Y();try{Dd(a,b,c,d,e,f,h)}catch(m){Z(g);if(m!==m+0)throw m;X(1,0)}}function Sc(a,b,c,d){var e=Y();try{return Fd(a,b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;X(1,0)}}var Hd;function Id(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ia=function Jd(){Hd||Kd();Hd||(Ia=Jd)};
function Kd(){function a(){if(!Hd&&(Hd=!0,k.calledRun=!0,!ka)){Na(Da);Na(Ea);aa(k);if(k.onRuntimeInitialized)k.onRuntimeInitialized();if(Ld){var b=k._main;try{var c=b(0,0);if(!noExitRuntime){if(k.onExit)k.onExit(c);ka=!0}ea(c,new Id(c))}catch(d){d instanceof Id||"unwind"==d||ea(1,d)}finally{}}if(k.postRun)for("function"==typeof k.postRun&&(k.postRun=[k.postRun]);k.postRun.length;)b=k.postRun.shift(),Fa.unshift(b);Na(Fa)}}if(!(0<E)){if(k.preRun)for("function"==typeof k.preRun&&(k.preRun=[k.preRun]);k.preRun.length;)Ga();
Na(Ca);0<E||(k.setStatus?(k.setStatus("Running..."),setTimeout(function(){setTimeout(function(){k.setStatus("")},1);a()},1)):a())}}k.run=Kd;if(k.preInit)for("function"==typeof k.preInit&&(k.preInit=[k.preInit]);0<k.preInit.length;)k.preInit.pop()();var Ld=!0;k.noInitialRun&&(Ld=!1);Kd();


  return ConfiguratorKernel.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = ConfiguratorKernel;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return ConfiguratorKernel; });
else if (typeof exports === 'object')
  exports["ConfiguratorKernel"] = ConfiguratorKernel;
